name: "Sync GHAS to Jira"

on:
  schedule:
    - cron: '*/1 * * * *' 

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: '${{ secrets.JIRA_URL }}'
          jira_user: '${{ secrets.JIRA_USER }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: 'TESTDEMO'
          sync_direction: 'gh2jira'
