name: "Sync GHAS to Jira"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: '${{ secrets.JIRA_URL }}'
          jira_user: '${{ secrets.JIRA_USER }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: 'TESTDEMO'
          sync_direction: 'gh2jira'
